{{- if .Values.inference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helios.inference.fullname" . }}
  labels:
    {{- include "helios.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
  {{- with .Values.inference.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.inference.service.type }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helios.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: inference
{{- end }}
