# Kustomization for KEDA resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trigger-auth.yaml
  - scaledobject-saleor.yaml
  - scaledobject-helios.yaml

commonLabels:
  app.kubernetes.io/part-of: helios
  app.kubernetes.io/component: autoscaling
