{{- if .Values.costIntelligence.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prescale.costIntelligence.fullname" . }}
  labels:
    {{- include "prescale.labels" . | nindent 4 }}
    app.kubernetes.io/component: cost-intelligence
  {{- with .Values.costIntelligence.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.costIntelligence.service.type }}
  ports:
    - port: {{ .Values.costIntelligence.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prescale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cost-intelligence
{{- end }}
