{{- if .Values.models.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prescale.fullname" . }}-models
  labels:
    {{- include "prescale.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.models.persistence.accessModes | nindent 4 }}
  {{- if or .Values.models.persistence.storageClass .Values.global.storageClass }}
  storageClassName: {{ .Values.models.persistence.storageClass | default .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.models.persistence.size }}
{{- end }}
